parameters:
    dp_menu.config.provider.class: Dp\ConfigMenuBundle\Provider\ConfigurationProvider
    dp_menu.menu.provider.class: Dp\ConfigMenuBundle\Provider\MenuProvider
    dp_menu.twig.extension.class: Dp\ConfigMenuBundle\Twig\DpMenuExtension

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true       # Allows optimizing the container by removing unused services; this also means
        # fetching services directly from the container via $container->get() won't work.
        # The best practice is to be explicit about your dependencies anyway.


    dp_menu.config.provider:
        class: '%dp_menu.config.provider.class%'
        public: true

    dp_menu.menu.provider:
        class: '%dp_menu.menu.provider.class%'
        public: true
        arguments:
          ['@service_container']

    dp_menu.twig.extension:
        class: '%dp_menu.twig.extension.class%'
        arguments: ['@service_container', '@twig.extension.assets']
        tags:
            - { name: twig.extension }